import 'package:flutter/material.dart';
import 'indexed_list_view.dart';

class MyApps extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

// ignore: must_be_immutable
class MyHomePage extends StatelessWidget {

  final itemHeight = 50.0;

  final items = [
    "Afghanistan",
    "Albania",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "AS",
    "Algeria",
    "Andorra",
    "Angola",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Brazil",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Indonesia",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "Netherlands",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
    "USA",
  ];

  String title;

  MyHomePage({
    @required
    this.title
  });

  Widget itemWidget(BuildContext context, int index) {
    return Column(
      children: [
        Text(items[index]),
        Text('punten]')
      ],
    );
  }

  Widget titleWidget(BuildContext context) {
    return Text(
      "Country List",
      textAlign: TextAlign.center,
      style: TextStyle(
          fontSize: 24.0
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: <Widget>[
            titleWidget(context),
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8.0),
                child: IndexedListView(
                  itemHeight: itemHeight,
                  items: items,
                  itemBuilder: itemWidget,
                ),
              ),
            )
          ],
        )
    );
  }
}